name: Java Unit Tests

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  actions: read
  dependencies: write


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adoptopen'
      - name: Run tests with Maven
        run: mvn test
